---
title: "Systematic Review Extraction Script Template"
date: "22 jan 2019 at 14:50:58"
output:
  html_document:
    self-contained: yes
    toc: false
params:
  rxsVersion = "0.1.0"
---

```{r rxsChunk-setup, include=FALSE, messages=FALSE}
### First load (and perhaps install) userfriendlyscience
if (!require('userfriendlyscience')) {
  install.packages('userfriendlyscience');
  require('userfriendlyscience');
}

### Other packages
safeRequire('ufs');              ### To flatten vectors with VecTxtQ in metabefor
safeRequire('googlesheets');     ### To import data from google sheets in metabefor
safeRequire('jsonlite');         ### To import a list of country codes in metabefor
safeRequire('data.tree');        ### To work with data structured in a tree in metabefor
safeRequire('pander');           ### To print the dataframe with results in a nice way
safeRequire('devtools');         ### To install metabefor from github repo
                                 ### ... Which we then do here:
devtools::install_github('Matherion/metabefor',
                         quiet=TRUE);
require('metabefor');            ### ... After which we load it

### Settings
knitr::opts_chunk$set(echo = FALSE);             ### Suppress R command printing
knitr::opts_chunk$set(comment=NA);               ### Suppress output prefix
pander::panderOptions('table.split.table', Inf); ### Disable table splitting
```

```{r rxsChunk-fieldnames}
eC <- list(titleCol="title",
           descriptionCol="description",
           identifierCol="identifier",
           valueTemplateCol="valueTemplate",
           validValuesCol="validValues",
           defaultCol="default",
           parentCol="parent",
           entityRefCol="entityRef",
           fieldRefCol="fieldRef",
           ownerCol="owner",
           listCol="list",
           collapsingCol="collapsing",
           repeatingCol="repeating",
           recurringCol="recurring",
           recursingCol="recursing",
           identifyingCol="identifying");

valueTemplateCols <- list(identifierCol="identifier",
                          descriptionCol="description",
                          validValuesCol="validValues",
                          defaultCol="default",
                          examplesCol="examples",
                          validationCol="validation",
                          errorCol="error");
```

```{r rxsChunk, echo=FALSE}
################################################################################
######################################################## START: study (ROOT) ###
################################################################################
study <- Node$new('study');
################################################################################

  ##############################################################################
  ########################################################### START: studyId ###
  ##############################################################################
  study$AddChild('studyId');
  study$studyId[['value']] <-
  ##############################################################################
  ### 
  ### STUDY IDENTIFIER
  ### 
  ### Unique identifier for this study
  ### 
  ##############################################################################
      
      "enter xdoi here"
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### For studies with a DOI, "doi:" directly followed by the DOI; for
  ### studies without a DOI, the DOI prefix of the publisher (see
  ### https://gist.github.com/TomDemeranville/8699224), followed by a
  ### slash, followed by the ISSN, followed by a dash, followed by the
  ### year of publication, followed by a dash, followed by the starting
  ### page. If no DOI prefix can be located, instead use 'NA'.
  ### 
  ### EXAMPLES:
  ### 
  ### "doi:10.18637/jss.v036.i03"
  ### "nodoi:10.1111/0965-2140/2003-951"
  ### "doi:10.1136/bmj.2.2288.1243"
  ### 
  ##############################################################################
  study$studyId[['validation']] <- expression(nchar(VALUE)>10);
  ##############################################################################
  ############################################################# END: studyId ###
  ##############################################################################


  ##############################################################################
  ########################################################## START: comments ###
  ##############################################################################
  study$AddChild('comments');
  study$comments[['value']] <-
  ##############################################################################
  ### 
  ### GENERAL COMMENTS
  ### 
  ### Any general comments the coder wants to add about this study
  ### 
  ##############################################################################
      
      ""
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### A single character value
  ### 
  ### EXAMPLES:
  ### 
  ### "example"
  ### "another example"
  ### 
  ##############################################################################
  study$comments[['validation']] <- expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1));
  ##############################################################################
  ############################################################ END: comments ###
  ##############################################################################


  ##############################################################################
  ########################################################### START: reviews ###
  ##############################################################################
  study$AddChild('reviews');
  study$reviews[['value']] <-
  ##############################################################################
  ### 
  ### INREVIEWS
  ### 
  ### The review or reviews that include this article.
  ### 
  ##############################################################################
      
      c("enter xdoi here", "enter a second xdoi here, or remove this")
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### For studies with a DOI, "doi:" directly followed by the DOI; for
  ### studies without a DOI, the DOI prefix of the publisher (see
  ### https://gist.github.com/TomDemeranville/8699224), followed by a
  ### slash, followed by the ISSN, followed by a dash, followed by the
  ### year of publication, followed by a dash, followed by the starting
  ### page. If no DOI prefix can be located, instead use 'NA'.
  ### 
  ### EXAMPLES:
  ### 
  ### c("doi:10.18637/jss.v036.i03", "nodoi:10.1111/0965-2140/2003-951")
  ### "doi:10.1136/bmj.2.2288.1243"
  ### 
  ##############################################################################
  study$reviews[['validation']] <- expression(all(nchar(VALUE)>10));
  ##############################################################################
  ############################################################# END: reviews ###
  ##############################################################################


  ##############################################################################
  ##################################################### START: yearPublished ###
  ##############################################################################
  study$AddChild('yearPublished');
  study$yearPublished[['value']] <-
  ##############################################################################
  ### 
  ### YEAR OF PUBLICATION
  ### 
  ### Year article was published
  ### 
  ##############################################################################
      
      NA
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### One year
  ### 
  ### EXAMPLES:
  ### 
  ### 2001
  ### 2002
  ### 1987
  ### 
  ##############################################################################
  study$yearPublished[['validation']] <- expression((is.numeric(VALUE) && (nchar(VALUE)==4)));
  ##############################################################################
  ####################################################### END: yearPublished ###
  ##############################################################################


  ##############################################################################
  ########################################################### START: authors ###
  ##############################################################################
  study$AddChild('authors');
  study$authors[['value']] <-
  ##############################################################################
  ### 
  ### AUTHORS
  ### 
  ### Authors of the article
  ### 
  ##############################################################################
      
      ""
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### A single character value
  ### 
  ### EXAMPLES:
  ### 
  ### "example"
  ### "another example"
  ### 
  ##############################################################################
  study$authors[['validation']] <- expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1));
  ##############################################################################
  ############################################################# END: authors ###
  ##############################################################################


  ##############################################################################
  ############################################################ START: emails ###
  ##############################################################################
  study$AddChild('emails');
  study$emails[['value']] <-
  ##############################################################################
  ### 
  ### EMAILS
  ### 
  ### Email addresses of the authors
  ### 
  ##############################################################################
      
      ""
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### A single character value
  ### 
  ### EXAMPLES:
  ### 
  ### "example"
  ### "another example"
  ### 
  ##############################################################################
  study$emails[['validation']] <- expression(is.na(VALUE) || (is.character(VALUE) && length(VALUE) == 1));
  ##############################################################################
  ############################################################## END: emails ###
  ##############################################################################


  ##############################################################################
  ########################################################### START: country ###
  ##############################################################################
  study$AddChild('country');
  study$country[['value']] <-
  ##############################################################################
  ### 
  ### COUNTRY
  ### 
  ### Country (or countries) where the data were collected
  ### 
  ##############################################################################
      
      NA
      
  ##############################################################################
  ########################################### VALUE DESCRIPTION AND EXAMPLES ###
  ##############################################################################
  ### 
  ### A character vector of the ISO 3166-1 alpha-2 country code(s)
  ### 
  ### EXAMPLES:
  ### 
  ### "NL"
  ### c("NL", "BE")
  ### 
  ##############################################################################
  study$country[['validation']] <- expression(is.na(VALUE) || (VALUE %in% countryCodeList()));
  ##############################################################################
  ############################################################# END: country ###
  ##############################################################################


  ##############################################################################
  ############################################################### START: app ###
  ##############################################################################
  study$AddChild('app');
  ##############################################################################
  ### 
  ### APPLICATION
  ### 
  ### Information about the e-health application
  ### 
  ##############################################################################
      
  
    ############################################################################
    ###################################################### START: app.device ###
    ############################################################################
    study$app$AddChild('app.device');
    ############################################################################
    ### 
    ### DEVICE
    ### 
    ### Device type for which the application was developed, e.g.
    ### 'smartwatch', 'vr', 'smartphone', etc
    ### 
    ############################################################################
        
        
    ############################################################################
    ######################################################## END: app.device ###
    ############################################################################
  
  
    ############################################################################
    #################################################### START: app.platform ###
    ############################################################################
    study$app$AddChild('app.platform');
    ############################################################################
    ### 
    ### PLATFORM
    ### 
    ### The platform, e.g. android, windows, etc
    ### 
    ############################################################################
        
        
    ############################################################################
    ###################################################### END: app.platform ###
    ############################################################################
  
      
  ##############################################################################
  ################################################################# END: app ###
  ##############################################################################


  ##############################################################################
  ####################################################### START: targetGroup ###
  ##############################################################################
  study$AddChild('targetGroup');
  ##############################################################################
  ### 
  ### TARGET GROUPS
  ### 
  ### Description of the target group(s) of the intervention
  ### 
  ##############################################################################
      
  
    ############################################################################
    ########################################################## START: tg.age ###
    ############################################################################
    study$targetGroup$AddChild('tg.age');
    ############################################################################
    ### 
    ### TARGET GROUP AGE
    ### 
    ### Age of the target group
    ### 
    ############################################################################
        
        
    ############################################################################
    ############################################################ END: tg.age ###
    ############################################################################
  
  
    ############################################################################
    ######################################################### START: tg.spec ###
    ############################################################################
    study$targetGroup$AddChild('tg.spec');
    ############################################################################
    ### 
    ### TARGET GROUP SPECIFICATION
    ### 
    ### Specification of the defining characteristics of this target
    ### group (e.g. a health issue, (sub-)culture, region, gender, etc)
    ### 
    ############################################################################
        
        
    ############################################################################
    ########################################################### END: tg.spec ###
    ############################################################################
  
      
  ##############################################################################
  ######################################################### END: targetGroup ###
  ##############################################################################


  ##############################################################################
  ########################################################### START: methods ###
  ##############################################################################
  study$AddChild('methods');
  ##############################################################################
  ### 
  ### METHODS
  ### 
  ### Description of the methods used by the study
  ### 
  ##############################################################################
      
  
    ############################################################################
    #################################################### START: isEvaluation ###
    ############################################################################
    study$methods$AddChild('isEvaluation');
    study$methods$isEvaluation[['value']] <-
    ############################################################################
    ### 
    ### EVALUATON
    ### 
    ### Whether this article describes the results of an evaluation
    ### (including effect size estimates) or not.
    ### 
    ############################################################################
        
        NA
        
    ############################################################################
    ######################################### VALUE DESCRIPTION AND EXAMPLES ###
    ############################################################################
    ### 
    ### A string that has to exactly match one of the values specified
    ### in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c(TRUE, FALSE)
    ### 
    ############################################################################
    study$methods$isEvaluation[['validation']] <- expression(is.na(VALUE) || (VALUE %in% c(TRUE, FALSE)));
    ############################################################################
    ###################################################### END: isEvaluation ###
    ############################################################################
  
  
    ############################################################################
    ########################################################## START: sample ###
    ############################################################################
    study$methods$AddChild('sample');
    ############################################################################
    ### 
    ### SAMPLE
    ### 
    ### Sample characteristics (for empirical articles)
    ### 
    ############################################################################
        
    
      ##########################################################################
      ############################################################# START: N ###
      ##########################################################################
      study$methods$sample$AddChild('N');
      study$methods$sample$N[['value']] <-
      ##########################################################################
      ### 
      ### SAMPLE SIZE
      ### 
      ### Total number of human participants in the study (note: the
      ### actual sample size may be larger if multiple observations
      ### are collected per participant)
      ### 
      ##########################################################################
          
          NA
          
      ##########################################################################
      ####################################### VALUE DESCRIPTION AND EXAMPLES ###
      ##########################################################################
      ### 
      ### Any valid whole number
      ### 
      ### EXAMPLES:
      ### 
      ### 30
      ### 8762
      ### 
      ##########################################################################
      study$methods$sample$N[['validation']] <- expression(is.na(VALUE) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1)));
      ##########################################################################
      ############################################################### END: N ###
      ##########################################################################
    
        
    ############################################################################
    ############################################################ END: sample ###
    ############################################################################
  
      
  ##############################################################################
  ############################################################# END: methods ###
  ##############################################################################

    
################################################################################
########################################################## END: study (ROOT) ###
################################################################################
class(study) <- c('rxs', class(study));
```


```{r rxsChunk-show-extracted-data, results='asis'}
print.rxs(study);
```

```{r rxsChunk-validation, results='asis'}
rxs_validation(study);
pandoc.header('Validation results', level=1)
#rxs_validation(study,
#               rxsStructure = fullResults$rxsStructure);
if (length(study$validationResults) > 2) {
  cat(paste0('- ', study$validationResults), sep='
');
} else {
  cat('Validation successful!');
}
```

